// Auto-generated by _integrate_js.py — per-page JS test specs.
export const SPECS = [
  { slug: "features/text-to-speech", mdx: "features/text-to-speech.mdx", cases: [{ name: "quick start", block: 0, file: ["hello.mp3", "mp3"] }] },
  { slug: "features/speech-to-text", mdx: "features/speech-to-text.mdx", cases: [{ name: "primary", block: 0 }] },
  { slug: "features/voice-cloning", mdx: "features/voice-cloning.mdx", cases: [{ name: "primary", block: 0 }] },
  { slug: "manage-voices", mdx: "features/manage-voices.mdx", cases: [{ name: "primary", block: 0 }] },
  { slug: "realtime-streaming", mdx: "features/realtime-streaming.mdx", cases: [{ name: "primary", block: 0, file: ["out.mp3", "mp3"] }] },
  { slug: "streaming-to-file", mdx: "developer-guide/sdk-guide/cookbook/streaming-to-file.mdx", cases: [{ name: "primary", block: 0, file: ["output.mp3", "mp3"] }] },
  { slug: "instant-voice-cloning", mdx: "developer-guide/sdk-guide/cookbook/instant-voice-cloning.mdx", cases: [{ name: "primary", block: 0, file: ["cloned.mp3", "mp3"] }] },
  { slug: "transcribe-to-captions", mdx: "developer-guide/sdk-guide/cookbook/transcribe-to-captions.mdx", cases: [{ name: "primary", block: 0, file: ["captions.srt", "srt"] }] },
  { slug: "batch-transcribe-with-language-hint", mdx: "developer-guide/sdk-guide/cookbook/batch-transcribe-with-language-hint.mdx", cases: [{ name: "primary", block: 0 }] },
  { slug: "telephony-8khz-audio", mdx: "developer-guide/sdk-guide/cookbook/telephony-8khz-audio.mdx", cases: [{ name: "primary", block: 0, file: ["out.wav", "wav"] }] },
  { slug: "developer-guide/sdk-guide/cookbook/clone-and-wait-until-ready", mdx: "developer-guide/sdk-guide/cookbook/clone-and-wait-until-ready.mdx", cases: [{ name: "primary", block: 0, file: ["out.mp3", "mp3"] }] },
  { slug: "oneshot-vs-persistent-cloning", mdx: "developer-guide/sdk-guide/cookbook/oneshot-vs-persistent-cloning.mdx", cases: [{ name: "primary", block: 0, file: ["oneshot.mp3", "mp3"] }] },
  { slug: "discover-library-voice", mdx: "developer-guide/sdk-guide/cookbook/discover-library-voice.mdx", cases: [{ name: "primary", block: 0, file: ["out.mp3", "mp3"], subs: { "<voice-id>": "<PUBLIC_VOICE>" } }] },
  { slug: "voice-agent-loop", mdx: "developer-guide/sdk-guide/cookbook/voice-agent-loop.mdx", cases: [{ name: "primary", block: 0, file: ["reply.mp3", "mp3"], subs: { "<voice-id>": "<PUBLIC_VOICE>" } }] },
];
